name: Build New Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'switch-pi-bot'

      - name: Create Custom pi-gen Stage
        run: |
          mkdir -p ${{ github.workspace }}/pi-gen/post-stage &&
          {
          cat > post-stage/00-prerun.sh <<-EOF
          #!/bin/bash
          cp -r ${{ github.workspace }}/switch-pi-bot/pi-gen/* ${{ github.workspace }}/pi-gen/post-stage/
          EOF
          } &&
          chmod -R +x ${{ github.workspace }}/pi-gen/post-stage

      - name: Build Pi Image
        uses: usimd/pi-gen-action@v1
        with:
          verbose-output: 'true'
          compression: 'xz'
          compression-level: '9'
          disable-first-boot-user-rename: '0'
          enable-noobs: 'false'
          enable-ssh: '0'
          github-token: '${{ github.token }}'
          hostname: 'pibot'
          image-name: 'switch-pibot'
          username: 'pi'
          password: ''
          pi-gen-dir: 'pi-gen'
          pi-gen-repository: 'RPi-Distro/pi-gen'
          pi-gen-version: 'arm64'
          release: 'bookworm'
          stage-list: 'stage0 stage1 stage2 post-stage'
          wpa-country: ''
          wpa-essid: ''
          wpa-password: ''

      - name: Get Release Details
        run: |
          TITLE=$(head -n 1 ./switch-pi-bot/changelog.txt)
          echo "RELEASE_TITLE=$TITLE" >> $GITHUB_ENV

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: 'true'
          title: ${{ env.RELEASE_TITLE }}
          files: |
            ./deploy/*.img.xz
            ./switch-pi-bot/changelog.txt