name: Build New Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:


jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Install Required Packages
        run: |
          modprobe loop
          echo $(lsmod | grep loop)
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y mount \
          sudo \
          bash \
          e2fsprogs \
          wget \
          xz-utils \
          util-linux \
          qemu-user-static

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'src'

      - name: Build Docker Image
        run: |
          update-binfmts --enable qemu-arm
          update-binfmts --enable qemu-aarch64
          docker build --platform linux/arm/v7 -t build-img:1.0 ./src/docker/.

      - name: Create Loopback Device
        run: |
          wget -O base.img.xz https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          xz -vd base.img.xz
          dd if=/dev/zero of=pi-bot.img bs=1M count=3900
          echo "LOOPBACK=$(losetup -f)" >> $GITHUB_ENV
          losetup -v ${{ env.LOOPBACK }} pi-bot.img
          echo "OLD_IMG=$(losetup -f)" > $GITHUB_ENV
          losetup -v ${{ env.OLD_IMG }} base.img
          dd if=${{ env.OLD_IMG }} of=${{ env.LOOPBACK }}
          parted ${{ env.LOOPBACK }} --script -- resizepart 2 100%
          echo "PI_ROOT=${{ env.LOOPBACK }}p2" >> $GITHUB_ENV
          e2fsck -yf ${{ env.PI_ROOT }}
          resize2fs ${ env.PI_ROOT }}
          rm base.img

      - name: Build Pi Image
        run: |
          mkdir -p finalsize
          docker run --rm -it --privileged \
          -e PI_ROOT=${{ env.PI_ROOT }}
          --platform linux/arm/v7 \
          -v ${{ env.PI_ROOT }}:${{ env.PI_ROOT }} \
          -v src:/src \
          -v finalsize:/finalsize \
          build-img:1.0

      - name: Shrink Image
        run: |
          echo "MIN_SIZE=$(cat finalsize/bytes)" >> $GITHUB_ENV
          echo "PARTED_SIZE=$((${{ env.MIN_SIZE }} / 1024 / 1024))M" >> $GITHUB_ENV
          parted ${{ env.LOOPBACK }} --script resizepart 2 ${{ env.PARTED_SIZE }}
          echo "END_SECTOR=$(fdisk -l "${{ env.LOOPBACK }}" | grep "${{ env.PI_ROOT }}" | awk '{print $3}'
          echo "IMG_SIZE=$((${{ env.END_SECTOR }} * 512))
          truncate --size=${{ env.IMG_SIZE }} pi-bot.img

      - name: Get Release Details
        run: |
          CHANGE=$(cat src/changelog.txt)
          echo "CHANGELOG=$CHANGE" >> $GITHUB_ENV
          TITLE=$(head -n 1 ${{ env.CHANGE }})
          echo "RELEASE_TITLE=$TITLE" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Alpha
          release_name: Alpha ${{ env.RELEASE_TITLE }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      - name: Add Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pi-bot.img
          asset_name: switch-pibot-${{ env.RELEASE_TITLE }}.img
          asset_content_type: application/octet-stream
