name: Build New Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip \
          dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
          qemu-utils kpartx gpg pigz

      - name: Enable ARM Interpreter
        run: |
          sudo update-binfmts --enable qemu-arm
          sudo update-binfmts --enable qemu-aarch64

      - name: Checkout pi-gen Repository
        uses: actions/checkout@v4
        with:
          repository: 'RPi-Distro/pi-gen'
          ref: bullseye-arm64

      - name: Clone Custom Post-Stage
        uses: actions/checkout@v4
        with:
          path: 'post-stage'
          sparse-checkout: |
            pi-gen

      - name: Import Extra Files
        uses: actions/checkout@v4
        with:
          path: 'extra'
          sparse-checkout: |
            changelog.txt
            config.txt

      - name: Get Release Details
        run: |
          TITLE=$(head -n 1 extra/changelog.txt)
          echo "RELEASE_TITLE=$TITLE" >> $GITHUB_ENV

      - name: Modify pi-gen
        run: |
          mv extra/config.txt config
          TITLE=$(head -n 1 extra/changelog.txt)
          echo "IMG_NAME='switch-pi-bot-${TITLE}'" >> config
          cat config
          rm -f stage2/EXPORT*
          rm -rf stage3
          rm -rf stage4
          rm -rf stage5

      - name: Build Image
        run: |
          CONTINUE=1 ./build-docker.sh

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: 'true'
          title: ${{ env.RELEASE_TITLE }}
          files: |
            deploy/*.img.xz
            extra/changelog.txt